name: 🚀 Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main        # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # so we can push tags/branches later

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (static export)
        run: |
          npm run build
          # Ensure public assets are copied and maintain directory structure
          mkdir -p out/images out/videos
          cp -r public/images/* out/images/ 2>/dev/null || true
          cp -r public/videos/* out/videos/ 2>/dev/null || true
          # Copy any other static files
          cp -r public/* out/ 2>/dev/null || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: false
          force_orphan: true
